### ISSUE TITLE
运行web_demo报错

### ISSUE THREAD

**Issue by lichenyigit** [FudanDISC/DISC-LawLLM#21]
报错信息如下：
![image](https://github.com/FudanDISC/DISC-LawLLM/assets/28697006/3cca96d3-0ffb-4102-bd83-3f85de826e04)
这个是上传到hf上的模型出问题了吗？

**Comment by yueshengbin** [comment]
你的网络有问题，连不上huggingface

**Comment by lichenyigit** [comment]
> 你的网络有问题，连不上huggingface

不应该啊，我用百川自己的模型就没问题

**Comment by lichenyigit** [comment]
方便留个联系方式吗？

**Comment by lichenyigit** [comment]
我把模型下载到本地，貌似压根加载不了，脚本仅支持hf加载
![image](https://github.com/FudanDISC/DISC-LawLLM/assets/28697006/b37083ce-4de3-477f-be35-2a93b2f5e4fc)

**Comment by lichenyigit** [comment]
搞定了，hf下载模型有问题，必须要下载到本地，我估计是因为里边有py文件导致的。没有依据，仅凭实验结果

**Comment by Charlie-XIAO** [comment]
Closing as completed.
