### ISSUE TITLE
Inconsistency between code and demo: no retrieval module

### ISSUE THREAD

**Issue by szdengdi** [FudanDISC/DISC-LawLLM#25]
“我们在 DISC-LawLLM 的基础上增加了一个基于开源检索框架 [Langchain-Chatchat](https://github.com/chatchat-space/Langchain-Chatchat) 的检索模块。”

没有提供langchain-chatchat的检索模块啊

**Comment by Charlie-XIAO** [comment]
The retrieval module is under development and not open sourced. Our evaluation results are obtained without the retrieval module as well.

**Comment by szdengdi** [comment]
You need to provide the source code for the retrieval module. 
Like this:
https://modelscope.cn/studios/wisdomOcean/wisdomInterrogatory/summary

**Comment by Charlie-XIAO** [comment]
I'm sorry but we have no plan for releasing our retrieval module. I hope you can understand that we cannot release all technical details of DISC-LawLLM, and it is kind of irresponsible to release the source code of a module that is still unmature and not fully validated.

If 智海-录问 has released their retrieval module, you can refer to theirs can create your own. You can also explore langchain-chatchat by yourself as we did. Note that 智海-录问 releasing their retrieval module does not necessarily mean we have to do so as well, and we hope for your understanding.
