### ISSUE TITLE
consultance of designed template

### ISSUE THREAD

**Issue by Connor-Shen** [FudanDISC/DISC-LawLLM#3]
"These candidate documents, along with the user input,
are formulated using our designed template and
then fed into the DISC-LawLLM"
请问是否会公布此处的模板样式以及具体的SFT训练方法？

**Comment by yueshengbin** [comment]
The details of the retrieved template are in Figure 3 (Model Input), and you can use our dataset to train your model with your own template.

**Comment by Charlie-XIAO** [comment]
Closing as completed.
