### ISSUE TITLE
在线demo测试 链接无法访问？

### ISSUE THREAD

**Issue by SUSTechIR** [FudanDISC/DISC-LawLLM#42]
非常欣赏您的工作，希望能够在线做一些测试，能否帮忙查看一下 “在线dmeo” 的服务器是不是出bug了？现在无法在网页在线体验产品了，希望收到您的答复，谢谢！

**Comment by yueshengbin** [comment]
最近服务器在维护，可能明天就可以了

**Comment by yueshengbin** [comment]
最近服务器在维护，已经可以了

**Comment by SUSTechIR** [comment]
> 最近服务器在维护，已经可以了
![image](https://github.com/FudanDISC/DISC-LawLLM/assets/107534147/0201ed86-0a93-4441-8a37-6be718608249)
知识库检索还是不行，麻烦帮忙看一下，谢谢

**Comment by SUSTechIR** [comment]
> 最近服务器在维护，已经可以了

![image](https://github.com/FudanDISC/DISC-LawLLM/assets/107534147/fbb341aa-aea1-43cf-80eb-ed78f1592625)
服务器磁盘满了，应该是

**Comment by SUSTechIR** [comment]
> 最近服务器在维护，已经可以了

您好，同学/老师，模型的访问还是首先，在线demo的方式无法使用，api调用也比原来慢，感谢帮忙检查下。祝好

**Comment by yueshengbin** [comment]
已经好了
