### ISSUE TITLE
Finetune code missing

### ISSUE THREAD

**Issue by yucc-leon** [FudanDISC/DISC-LawLLM#5]
没有看到src目录

**Comment by yueshengbin** [comment]
If using our example footsteps, refer to LLaMA-Efficient-Tuning. otherwise, follow MedLLM's instructions for use!

**Comment by Charlie-XIAO** [comment]
关于模型微调的方式，已在 [README](https://github.com/FudanDISC/DISC-LawLLM#%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83) 中给出样例。

> 开发者可以对 DISC-LawLLM 进行微调使用。在此可以参照与 DISC-LawLLM 兼容的微调工具 [LLaMA Efficient Tuning](https://github.com/hiyouga/LLaMA-Efficient-Tuning) 或是我们的 [DISC-MedLLM](https://github.com/FudanDISC/DISC-MedLLM) 医疗大模型。

您需要下载 [LLaMA Efficient Tuning](https://github.com/hiyouga/LLaMA-Efficient-Tuning)。`src` 目录并不在我们的仓库中。

**Comment by Charlie-XIAO** [comment]
In particular, `src/` is under [LLaMA Efficient Tuning](https://github.com/hiyouga/LLaMA-Efficient-Tuning) repository. You need to clone it to follow our examples, as is also specified in README.

**Comment by Charlie-XIAO** [comment]
Closing as completed.
